// Configuration file (sonar-project.properties)
project.org=nscs
sonar.host.url=https://sonar.us.oracle.com
# must be unique in a given SonarQube instance
# Key Format for NS CS Utility / Common Customization : nscs.{customer-number}-{technical-area}
sonar.projectKey=nscs.7546000-ecom
# this is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=Illumination Enterprises Inc-7546000-ecom
sonar.projectVersion=0.1
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.sources=./extensions/Workspace
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/Workspace/Extras/**
sonar.eslint.reportPaths=./reports/lint_report.json
sonar.dependencyCheck.skip=true