define('DoNotEmail.Newsletter.Model', [
    'Newsletter.Model',
    'underscore'
], function DoNotEmailNewsletterModel(
    NewsletterModel,
    _
) {
    'use strict';

    return _(NewsletterModel).extend({
        subscribe: function subscribe(email) {
            this.validate({ email: email });

            // Removed the duplicate criteria detection as it was conflicting with
            // a valid use case generated by the Klaviyo integration
            return this.createSubscription(email);
        }
    });
});
