SELECT TOP (1000) [ID_OPR]
      ,[PW_ACS_OPR]
      ,[LN_PRS]
      ,[FN_PRS]
      ,[ID_SSN]
      ,[TS_EF]
      ,[TS_EP]
      ,[ID_GP_WRK]
      ,[DE_GP_WRK]
      ,[ID_BSN_UN]
      ,[NM_BSN_UN]
      ,[ID_WRKR]
      ,[PW_ACS_WRKR]
      ,[TY_WRKR]
      ,[ID_PRTY]
      ,[ID_CT]
  FROM [RAPOS].[dbo].[RA_Operator] where ID_OPR='Idaniele'